#version: "3.8"
services:
    mlflow:
        build: 
            context: ./mlflow
            dockerfile: Dockerfile
        container_name: mlflow
        ports: 
          - 7777:7777
        volumes:
            - ./mlruns:/mlflow/mlruns
        environment:
            - HOST_IP="0.0.0.0"
            - MLFLOW_ARTIFACT_ROOT=/mlflow/mlruns
        command: mlflow server --host=0.0.0.0 --port=7777 --default-artifact-root /mlflow/mlruns
    prefect: 
        image: prefecthq/prefect:2.20-python3.11
        ports:
            - "4200:4200"
        environment:
            - HOST_IP="0.0.0.0"
            - PREFECT_HOME=/.prefect
        depends_on:
            - mlflow
        volumes:
            - ./prefect_storage:/.prefect
        command: prefect server start --host 0.0.0.0  
